### ISSUE TITLE
Issue with GUI dependent modules

### ISSUE THREAD

**Issue by hmandle** [CBICA/Deep-LIBRA#6]
Hi, I am trying to run the GUI but can't seem to get some of the modules working. My code is below. TIA! 
-------------------------------------------------------------------------------------------------------------------------
(base) C:\Users\ANONYMOUS>conda create --name DeepLIBRA python=3.10
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\ANONYMOUS\AppData\Local\anaconda3_l\envs\DeepLIBRA

  added / updated specs:
    - python=3.10

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-23.0.1                 |  py310haa95532_0         2.8 MB
    python-3.10.10             |       h966fe2a_2        15.7 MB
    sqlite-3.41.1              |       h2bbff1b_0         897 KB
    ------------------------------------------------------------
                                           Total:        19.4 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/win-64::bzip2-1.0.8-he774522_0
  ca-certificates    pkgs/main/win-64::ca-certificates-2023.01.10-haa95532_0
  certifi            pkgs/main/win-64::certifi-2022.12.7-py310haa95532_0
  libffi             pkgs/main/win-64::libffi-3.4.2-hd77b12b_6
  openssl            pkgs/main/win-64::openssl-1.1.1t-h2bbff1b_0
  pip                pkgs/main/win-64::pip-23.0.1-py310haa95532_0
  python             pkgs/main/win-64::python-3.10.10-h966fe2a_2
  setuptools         pkgs/main/win-64::setuptools-65.6.3-py310haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.41.1-h2bbff1b_0
  tk                 pkgs/main/win-64::tk-8.6.12-h2bbff1b_0
  tzdata             pkgs/main/noarch::tzdata-2022g-h04d1e81_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/win-64::wheel-0.38.4-py310haa95532_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py310haa95532_2
  xz                 pkgs/main/win-64::xz-5.2.10-h8cc25b3_1
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_0

Proceed ([y]/n)? y

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate DeepLIBRA
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) C:\Users\ANONYMOUS>conda activate DeepLIBRA

(DeepLIBRA) C:\Users\ANONYMOUS>pip install -r requirements.txt
Collecting h5py==2.9.0
  Using cached h5py-2.9.0.tar.gz (287 kB)
  Preparing metadata (setup.py) ... done
Collecting Keras==2.2.4
  Using cached Keras-2.2.4-py2.py3-none-any.whl (312 kB)
Collecting Keras-Applications==1.0.8
  Using cached Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
Collecting Keras-Preprocessing==1.1.0
  Using cached Keras_Preprocessing-1.1.0-py2.py3-none-any.whl (41 kB)
Collecting matplotlib==3.1.0
  Using cached matplotlib-3.1.0.tar.gz (37.2 MB)
  Preparing metadata (setup.py) ... done
Collecting MedPy==0.4.0
  Using cached MedPy-0.4.0.tar.gz (151 kB)
  Preparing metadata (setup.py) ... done
Collecting numpy==1.16.4
  Using cached numpy-1.16.4.zip (5.1 MB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.0.25 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72)
ERROR: No matching distribution found for opencv-python==4.1.0.25

(DeepLIBRA) C:\Users\ANONYMOUS>py run_GUI.py
Traceback (most recent call last):
  File "C:\Users\ANONYMOUS\run_GUI.py", line 4, in <module>
    from GUI import Ui_Form
  File "C:\Users\ANONYMOUS\GUI.py", line 3, in <module>
    from libra import *
  File "C:\Users\ANONYMOUS\libra.py", line 9, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'

**Comment by omaghsoudi** [comment]
try - python=3.8 instead of - python=3.10
